[project]
name = "rock-club"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "blacksheep>=2.0.7",
    "piccolo[all]>=1.22.0",
    "pydantic-settings>=2.6.1",
    "pydantic>=2.9.2",
    "uvicorn>=0.32.0",
]
